---
version: "2"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    restart: always
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    volumes:
      - ~/Documents/DI/sont/saved_index/data:/usr/share/elasticsearch/data
  sont:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - elastic
    ports:
    - 3000:80
