version: '2'

networks:
  sont_network:
    external:
      name: nginxproxynetwork
  soundtoll:
    external:
      name: soundtoll_default

services:
  elastic:
    image: registry.diginfra.net/elasticsearch:7.5.2-patched
    container_name: soundtoll_es
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
    expose:
      - 9200
    networks:
      - sont_network
    volumes:
      - /data/docker/volumes/sont_es/_data:/usr/share/elasticsearch/data
      - /home/robz:/home


  sont:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: soundtoll_application
    restart: always
    environment:
      - VIRTUAL_HOST=sont.sd.di.huc.knaw.nl
    links:
      - elastic
      - sont_mysql
    volumes:
      - /home/robz:/home
    networks:
      - sont_network
      - soundtoll